#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Holberton School\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
